# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Applicant.AI' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Applicant.AI
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'OneSignal', '>= 2.6.2', '< 3.0'

  target 'Applicant.AITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Applicant.AIUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OneSignalNotificationServiceExtension' do
    inherit! :search_paths
    pod 'OneSignal', '>= 2.6.2', '< 3.0'
  end
  
end
